# -*- coding: utf-8 -*-
"""Loading

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-8ORja8IyJcX852St9RtZ-L4JIP6HTW
"""

!pip install --upgrade gspread

"""Connect to Google Sheets and store it in a variable wb (workbook)

"""

from google.colab import auth
auth.authenticate_user()
import gspread
from google.auth import default
creds, _ = default()
import pandas as pd

gc = gspread.authorize(creds)

wb = gc.open_by_key('1lLdibiVIFJH2oJb3FTFJQAvjH-hK3lalXxQw_Z4C0_E')

ws = wb.worksheet('Table')

# get_all_values gives a list of rows.
rows = ws.get_all_values()

# Convert to a DataFrame and render.
dfTable = pd.DataFrame.from_records(rows[1:],columns=rows[0])
print(dfTable)

wsTest = wb.worksheet('TestTable')

# get_all_values gives a list of rows.
rowstest = wsTest.get_all_values()

# Convert to a DataFrame and render.
dfTest = pd.DataFrame.from_records(rowstest[1:],columns=rowstest[0])
print(dfTest)

dfCombined = pd.merge(dfTable,dfTest,how="inner",on="Index")
print(dfCombined)

IofLists = dfCombined.to_numpy().tolist()
print(IofLists)

headers = dfCombined.columns.to_list()

dataToWrite = [headers] + IofLists
print(dataToWrite)

wsResults = wb.worksheet('Results')

wsResults.update("A1",dataToWrite)